# Generated by Django 5.2.9 on 2026-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_body_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
